### ISSUE TITLE
Hard-coded Azure global URI 'https://login.windows.net/' in cdm.storage.ADLSAdapter

### ISSUE THREAD

**Issue by simonzhaoms** [microsoft/CDM#228] opened 2021-03-15 09:46 UTC
Hi, I am using [ADLSAdapter](https://github.com/microsoft/CDM/blob/ff16898e1db8f3822207c581709192cc8c72845b/objectModel/Python/cdm/storage/adls.py#L29) in CDM SDK for Python to load data from ADLS located in Azure China.  I found the URI for [`_auth_context`](https://github.com/microsoft/CDM/blob/ff16898e1db8f3822207c581709192cc8c72845b/objectModel/Python/cdm/storage/adls.py#L71) is hard-coded with `https://login.windows.net/`, which may be `https://login..chinacloudapi.cn` for Azure China.

See [Azure China developer guide](https://docs.microsoft.com/en-us/azure/china/resources-developer-guide) for more details.

**Comment by victor-gutemberg** [comment] 2021-03-15 14:56
Hello @simonzhaoms,

thanks for reporting this issue. I'll raise this issue internally and I'll let you know once we have an estimate about when we can make this configurable.

**Comment by mfriscia7** [comment] 2021-03-22 20:34
Hi @simonzhaoms,
Just giving you an update, we have planned to fix this issue during the month of April. So you should expect that as a part of our April release.

**Comment by simonzhaoms** [comment] 2021-03-26 09:25
Thanks @mfris

**Comment by simonzhaoms** [comment] 2021-03-26 09:27
Thanks @mfris

**Comment by simonzhaoms** [comment] 2021-03-26 09:28
Thanks @mfriscia7

**Comment by llawwaii** [comment] 2021-04-20 06:57
Hi @simonzhaoms ,

We are working on migrating from ADAL to MSAL. In MSAL, the [new API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.abstractacquiretokenparameterbuilder-1.withauthority?view=azure-dotnet#Microsoft_Identity_Client_AbstractAcquireTokenParameterBuilder_1_WithAuthority_Microsoft_Identity_Client_AzureCloudInstance_System_String_System_Boolean_) `public T WithAuthority (Microsoft.Identity.Client.AzureCloudInstance azureCloudInstance, string tenant, bool validateAuthority = true);` allows customers to put their target [AzureCloudInstance](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.azurecloudinstance?view=azure-dotnet). We are planning to update the ADLS adapter constructor to include this AzureCloudInstance Enum. However, the problem is that we don't have a test environment located in Azure China. Could you please help? Is there any chance that I could contact you internally on Teams? Please let me know. Thanks!

**Comment by llawwaii** [comment] 2021-10-05 17:36
Hi @simonzhaoms,

We have a new constructor [ADLSAdapter(string, string, string, string, string, AzureCloudEndpoint)](https://docs.microsoft.com/en-us/common-data-model/1.0om/api-reference/storage/adlsadapter#constructors), where the optional param [AzureCloudEndpoint](https://docs.microsoft.com/en-us/common-data-model/1.0om/api-reference/cdm/azurecloudendpoint) gives you options to choose which region you need, it is assigned to Public by default. You can also pass this value via config.json. Let me know if you have more questions. Thanks!

**Closed by llawwaii** 2021-10-05 17:36 UTC
