### ISSUE TITLE
Exception unknown url type when using ADLSAdapter

### ISSUE THREAD

**Issue by jpvillemalard** [microsoft/CDM#297] opened 2022-02-24 21:40 UTC
https://github.com/microsoft/CDM/blob/6adbae0554f5cca0d6796558a85466f72d28b947/objectModel/Python/cdm/utilities/network/cdm_http_client.py#L82

We had to manually add the network protocol 

```
        if self._api_endpoint is not None:
            full_url = self._combine_urls(self._api_endpoint, cdm_request.requested_url)
        else:
            full_url = "https://" + cdm_request.requested_url
```

to upload the CDM folder structure to our Azure Data Lake Storage Generation 2 container or else we would be getting the following message

`ERROR CdmCorpusDefinition | Failed to compute last modified time for partition file /<MODULE_NAME_REDACTED>.manifest.cdm.json. Exception unknown url type: '<STORAGE_ACCOUNT_REDACTED>.dfs.core.windows.net/<CONTAINER_NAME_REDACTED>/<ROOT_FOLDER_REDACTED>/<MODULE_NAME_REDACTED>.manifest.cdm.json?<SAS_TOKEN_REDACTED>' | _get_last_modified_time_from_object_async | adls:/<MODULE_NAME_REDACTED>.manifest.cdm.json`

**Comment by dingbx** [comment] 2022-02-25 23:10
Thanks for letting us know! Can you please also provide how you initialize the adlsAdapter?

**Comment by jpvillemalard** [comment] 2022-02-25 23:13
`adls_adapter = ADLSAdapter(hostname=payload['hostname'], root=payload['module'], sas_token=payload['sas_token'])`

**Comment by jpvillemalard** [comment] 2022-02-25 23:18
`payload['hostname']` is of the format `https://<storage account>.blob.core.windows.net/<container>`

**Comment by dingbx** [comment] 2022-02-28 21:34
Hi,

I'm checking this issue now and wanted to confirm the version of the python sdk you used. Is it the latest master branch version in GitHub?

Thanks,
Yjing

**Comment by jpvillemalard** [comment] 2022-02-28 21:35
Yes it is https://pypi.org/project/commondatamodel-objectmodel/ which points to https://github.com/microsoft/CDM/tree/master/objectModel/Python

**Comment by dingbx** [comment] 2022-02-28 21:37
Thanks, I'll try to reproduce this error.

**Comment by dingbx** [comment] 2022-02-28 22:49
And can you please also specify the api you called when this error is thrown? Is it compute_last_modified_time_async? file_status_check_async? I just tested and found it working.

Can you please try changing the hostname to <storage account>.dfs.core.windows.net and the root to <container>/<folder>? sas_token should be the same.

e.g. 
ADLSAdapter(hostname='storageaccounttest.dfs.core.windows.net', root='containername/foldername',
                           sas_token='?sv=xxxxxxx')

**Comment by dingbx** [comment] 2022-02-28 23:10
It seems that if the hostname has https:// in the beginning, the full_url is not constructed correctly. I've filed a bug for this issue, a temporary fix is to remove it from the constructor. Please let me know if it works for you, thanks!

**Comment by jpvillemalard** [comment] 2022-02-28 23:51
That seems to work. Thanks for the workaround. However, how do you save the manifest back to the ADLS Gen 2 container? We are seeing the following error 

`WARNING CdmDataPartitionPatternDefinition | Failed to fetch all files in the folder location 'adls:/<TABLE_NAME_REDACTED>.parquet' described by a partition pattern. Exception: HTTP Error 400: Value for one of the query parameters specified in the request URI is invalid. | file_status_check_async | adls:/<MODULE_REDACTED>.manifest.cdm.json/`

And that is defined in our code as 

```
    logging.info("Configure storage adapters")
    adls_adapter = ADLSAdapter(hostname=payload['hostname'], root=payload['module']
                              , sas_token=payload['sas_token'])
    corpus.storage.mount("adls", adls_adapter)

    # Get a reference to the root folder under the 'local' namespace (where LocalAdapter points at)
    root_folder = corpus.storage.fetch_root_folder("adls")

    # Now it's time to create manifest object which acts as a folder descriptor. We'll place it also at the root
    manifest = corpus.make_object(
        CdmObjectType.MANIFEST_DEF, "manifest"
    )  # type: CdmManifestDefinition
    root_folder.documents.append(manifest)

    entity_definitions(corpus, root_folder, manifest, modules)

    # Resolve the manifest - since entities, data types and traits have inheritance
    # and we want to 'flatten' all that
    # We specify also a folder and naming pattern for the resolved document
    manifest_resolved = await manifest.create_resolved_manifest_async(
        f"{payload['module']}", "{n}.parquet/{n}.cdm.json"
    )

    await entity_partitions(corpus, manifest_resolved)

    # Save the manifest and the associated entity
    await manifest_resolved.save_as_async(
        f"{payload['module']}.manifest.cdm.json", True
    )
```

**Comment by dingbx** [comment] 2022-03-01 01:15
First of all, I want to make sure I understand your purpose. You are creating a manifest with entities and partitions in the code and you would like to save the manifest.cdm.json and entity.cdm.json to the file system? Do you already have all the partitions file available in the file system?

And what does entity_definitions and entity_partitions do? Do they create entity definitions and add it to the manifest and the folder?

You can also check our sample code for creating manifest. https://github.com/microsoft/CDM/blob/master/samples/2-create-manifest/code-python/main.py

**Comment by jpvillemalard** [comment] 2022-03-01 13:20
Yes. We are trying to create the manifest file with entities and partitions in the code but trying to save the manifest, entities and partitions in the ADLS container. The partitions are parquet files that will also be in the ADLS container.

`entity_definitions` will define the entities in the manifest and model files. `entity_partitions` will define the partitions for each entity.

We have already checked that `main.py` example, which helped us define our code using LocalAdapter. However, there are no examples explaining how to use ADLSAdapter.

**Comment by Venkata1920** [comment] 2022-03-01 19:41
Hi @jpvillemalard, could you let us know which method is actually failing with the error? It looks like the partition file is not in the ADLS folder yet. Could you verify that the parquet files are present in the ADLS folder? Thanks!

**Comment by jpvillemalard** [comment] 2022-03-01 19:44
Ah. The partition files need to be present before generating the CDM files? We were not aware of that. We thought we could generate the files regardless of the partition files being present or not.

**Comment by Venkata1920** [comment] 2022-03-01 19:48
Hi @jpvillemalard, yes, the partition files need to be present since they are being referenced with the ADLS namespace. If you see issues after copying the files to ADLS folder (other than the protocol prefix that we will work on fixing soon), then please do get back on the thread. If not, please feel free to close the issue.

**Comment by Venkata1920** [comment] 2022-03-07 20:40
Closing this issue. @jpvillemalard , if there are additional asks / requests, then please open a new ticket.

**Closed** 2022-03-07 20:39 UTC
