### ISSUE TITLE
[Question] A Party entity?

### ISSUE THREAD

**Issue by carld** [microsoft/CDM#181] opened 2020-09-24 22:13 UTC
Hi,

I have looked at a few reference data models (http://www.databaseanswers.org/data_models/index.htm, https://www.univdata.com/articles) and often noticed a Party entity which acts as a super type for entities such as Person, Organisation, Contact etc.

The CDM doesn't appear to have a Party entity in the core schema, and I was wondering if this is deliberate and what the thinking behind that or modelling process was to discover the CDM is. I appreciate this may be somewhat academic.

Any links to design principles or methodology behind CDM would be much appreciated. Even a commentary on the trade-offs for having or not a Party entity would interest me.

Thanks!

**Comment by dingbx** [comment] 2020-09-28 21:25
Hi carld,

Thanks for your question. You can find more documentation in [https://docs.microsoft.com/en-us/common-data-model/](https://docs.microsoft.com/en-us/common-data-model/). The original design of CDM entities are heavily influenced by Dynamics 365. 

For more information, our architect who is out of office at the moment should be able to answer your question. Please expect some delay for the reply.

**Comment by mfriscia7** [comment] 2020-10-15 16:45
Hi carld,

I am not the architect but I can confirm that the data models are based off of the schemas that are present in Dynamics 365.

**Comment by jeremyjh** [comment] 2020-10-15 16:55
@mfriscia7 Yes but the question is why for Dynamics 365 is there no Party concept?

> I was wondering if this is deliberate and what the thinking behind that or modelling process was to discover the CDM is. I appreciate this may be somewhat academic.
> 
> Any links to design principles or methodology behind CDM would be much appreciated. Even a commentary on the trade-offs for having or not a Party entity would interest me.

**Comment by mfriscia7** [comment] 2020-10-15 17:29
That is a question for the Dynamics 365 team, I do not know the reasons behind their decision making. That being said, you do not have to use those schemas to use CDM. Those schemas are useful if you are using Microsoft apps where that shape of data is used, but they are not a requirement for using CDM.

**Comment by dingbx** [comment] 2020-10-26 21:46
Closing for lack of response, please reopen if you want to continue discussing.

**Comment by carld** [comment] 2020-10-28 03:31
Hi, I did not respond because I was waiting on a response from the architect as per the earlier comment:

> For more information, our architect who is out of office at the moment should be able to answer your question. Please expect some delay for the reply.

If it would be better to contact the D365 team please let me know the best approach?

Thanks,
Carl

**Comment by dingbx** [comment] 2020-10-29 19:25
Hi Carl, thanks for your patience. Reopening this issue since question not solved yet. 

I have forwarded your request and waiting for reply from D365.

**Comment by dingbx** [comment] 2020-10-29 20:26
According to CDS team,

“The Party entity is not part of standard CDS. It can be introduced into a CDS org by importing certain solutions associated with the Dual Write feature of F&O, but those solutions are considered to be customizations at this time and therefore are not included in the CDM specification for CDS.

F&O schema is documented separately in CDM under “[operationsCommon](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fcommon-data-model%2Fschema%2Fcore%2Foperationscommon%2Foverview&data=04%7C01%7CYijing.Ding%40microsoft.com%7C2abd7eb9340241d4bb7508d87c4571c7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637395984984072912%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FC27UC8fNB8BSMtQ2auje1K3zKmSI5Y5JiCnTcKOH%2B4%3D&reserved=0)”  which includes the [Party](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fcommon-data-model%2Fschema%2Fcore%2Foperationscommon%2Fentities%2Fcommon%2Fgab%2Fdirpartybaseentity&data=04%7C01%7CYijing.Ding%40microsoft.com%7C2abd7eb9340241d4bb7508d87c4571c7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637395984984082908%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LORF1B%2ByO1P0INN2v3JGG34ppeCQIlAZ89MA%2BSx5nM4%3D&reserved=0) entity and associated framework.”

**Comment by carld** [comment] 2020-11-02 00:10
Thanks for this answer. What is F&O? Thanks

**Comment by carld** [comment] 2020-11-02 00:21
I see a data model that includes a Party entity in the Global Address Book (GAB) documentation. For others who come this way, there is a view of it here  https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/fin-ops/organization-administration/overview-global-address-book?toc=/dynamics365/commerce/toc.json

**Comment by dingbx** [comment] 2020-11-02 17:37
@carld, F&O is Finance and Operations and thanks for putting the link here. 

Closing this issue.

**Closed by dingbx** 2020-11-02 17:37 UTC
