### ISSUE TITLE
unable to read the manifest in typescript ( having Typescript SDK  issues)

### ISSUE THREAD

**Issue by gauthammekala** [microsoft/CDM#175] opened 2020-08-24 07:45 UTC
Hi,

Can you please help in reading manifest in typescript ( i have tried but end up with a lot of undefined issues  ) if possible can you please update reading manifest sample in typescript.

**Comment by llawwaii** [comment] 2020-08-27 18:03
Hi,
Currently, we don't have this sample in typescript. Can you please look at the existing samples in C# and Java? Let me know if you have more questions. Thanks.

**Comment by gauthammekala** [comment] 2020-08-28 08:59
I'm trying to use typescript SDK  to read the manifest (i  follow the same logic of the C# ) But I end up with undefined issues ... Please find the attached files for the same

[typescript.zip](https://github.com/microsoft/CDM/files/5141099/typescript.zip)

**Comment by llawwaii** [comment] 2020-08-28 18:45
Hi,

Can you tell me which version of the Typescript SKD you are using? Thanks.

**Comment by JeffBern** [comment] 2020-08-28 20:32
The code looks right. Can you use the setEventCallback method on the corpus to register a listener and print out any error messages?

**Comment by gauthammekala** [comment] 2020-08-31 11:32
<img width="950" alt="Screenshot 2020-08-31 at 13 30 30" src="https://user-images.githubusercontent.com/70132800/91715576-324cd180-eb8e-11ea-9043-cf849f92a1ca.png">

I have the setEventCallback method but it showing error 3 what does it mean?

**Comment by JeffBern** [comment] 2020-08-31 18:18
I loaded you schema definitions using my copy of our TS code and everything looked good, so something simple I think.  The text I see above looks like the error message is not being shown. If you put your own code in for the setEventCallback routine, then you can print the full message out.

**Comment by gauthammekala** [comment] 2020-09-01 09:37
Many thanks for your response 🙏  
 even I'm trying with Microsoft CDM samples data but still, I'm not able to properly read the manifest (DataFormat showing numbers )Please find the attached files for more information  (i believe I did a mistake somewhere but I don't know where.... Can you  please help me on this )


![Screenshot 2020-09-01 at 11 25 44](https://user-images.githubusercontent.com/70132800/91832889-418f5600-ec46-11ea-82b9-7872bd2ac116.png)
[typescript.zip](https://github.com/microsoft/CDM/files/5155294/typescript.zip)

**Comment by mfriscia7** [comment] 2020-09-01 18:09
Hi, it appears that it is unable to find the basic traits found in our cdm schemas (such as "is.dataFormat.character"). I do not have your schemas in front of me, but are you missing the following import in your schemas?

```
{
    "corpusPath": "cdm:/foundations.cdm.json"
}
```

**Comment by gauthammekala** [comment] 2020-09-04 07:58
HI,

Many thanks 🙏 for your valuable support is highly appreciated 🙏 
even tried with Microsoft sample JSON files (
https://github.com/microsoft/CDM/tree/master/samples/example-public-standards
) but still, I'm getting DataFormat in number (i need anything to add to get actual datatype like integer, string.... )
[typescript.zip](https://github.com/microsoft/CDM/files/5173430/typescript.zip)

**Comment by mfriscia7** [comment] 2020-09-08 18:48
Since the dataFormat field is an enum type, you should be able to use the following to get the string version of the dataFormat:

`cdmDataFormat[attribute.dataFormat]`

Let me know if that works for you.

**Comment by SukanyaSrinivasan** [comment] 2020-09-14 08:25
Hi,
Closing this item as a solution has been provided. Please re-open if the issue is not addressed.

**Closed by SukanyaSrinivasan** 2020-09-14 08:25 UTC
