### ISSUE TITLE
Datatype issues in Sustainability CDM

### ISSUE THREAD

**Issue by lnewportmsft** [microsoft/CDM#328] opened 2022-06-29 18:20 UTC
For example, under Emissions, the following attributes are listed as dateTime:

calculationdate
consumptionenddate
consumptionstartdate
transactiondate

However, it is necessary on import to apply a datatype transformation to "date" in PowerQuery for the import to succeed.  Absent this transformation the import fails.

Should these be "date" in the Sustainability CDM?

**Comment by scheyal** [comment] 2022-07-05 20:46
Refer to the following for date behavior:

https://docs.microsoft.com/en-us/power-apps/maker/data-platform/behavior-format-date-time-field

It can be discovered by examining dataverse backend - 

<img width="249" alt="image" src="https://user-images.githubusercontent.com/8867670/177413377-3a755deb-47de-487b-8c2b-354d564fa04b.png">

**Comment by scheyal** [comment] 2022-09-21 20:21
The failure is b/c Calculation date is missing. It should work just fine otherwise.

**Comment by andresravinet** [comment] 2022-09-22 00:46
> The failure is b/c Calculation date is missing. It should work just fine otherwise.

I'm not sure you understand what issue we're trying to get resolved here.

**Comment by scheyal** [comment] 2022-10-11 23:44
I don't see the issue here. Maybe you can explain in details again?

I tried a repro with the link. 

That XLS was missing calc date (was null).
When I import it (no manual or auto-mapping), PQ does a transformation as follows (and just succeeds):

XLS: 
![image](https://user-images.githubusercontent.com/8867670/195218022-f486987f-cea3-4059-ad72-12a246ee569d.png)

PQ view (not edited):
![image](https://user-images.githubusercontent.com/8867670/195216462-3c3139a1-15b4-4bbe-b904-9393a73c492e.png)

**Comment by dingbx** [comment] 2022-10-19 22:07
Hi, 

Just wanted to check the current status of this issue. Has the issue been resolved?

If I understand it correctly, the issue is the schema in Map to CDM dialog which the source data has been mapped to, has some of the attributes defined with datetime, but their type should be date.

and these attributes are:
- calculationdate
- consumptionenddate
- consumptionstartdate
- transactiondate

If this is the problem, then sustainability team can check their schema and update them if those types should be date or not. And if this is not the problem, it might be the validation should also accept datetime.

**Comment by dingbx** [comment] 2022-12-13 18:45
Closing this issue since the explanation was provided through email, please reopen if the issue is not resolved.

**Closed by dingbx** 2022-12-13 18:45 UTC
