### ISSUE TITLE
If you have NOT already done so, Please incorporate ISA 95 / IEC 62264 Control to Enterprise Data Integration Model

### ISSUE THREAD

**Issue by BillBosler** [microsoft/CDM#341] opened 2022-10-25 10:28 UTC
This Industry Agnostic Set of Standards defines a Common Data Schema for ERP to be able to Commit to a Delivery Date, Communicate with Production, etc. It is the basis for B2MMl and part of Germany's Industry 4.0 Efforts.

Incorporating this into MS' CDM will advance the CDM significantly.

"B2MML is an XML implementation of the ANSI/ISA-95, Enterprise-Control System Integration, family of standards (ISA-95), known internationally as IEC/ISO 62264. B2MML consists of a set of XML schemas written using the World Wide Web Consortium's XML Schema language (XSD) that implement the data models in the ISA-95 standard.

Companies interested in following ISA-95 for integration projects may use B2MML to integrate business systems such as ERP and supply chain management systems with manufacturing systems such as control systems and manufacturing execution systems. B2MML is a complete implementation of ISA-95. Any company may use B2MML royalty-free, provided credit is given to MESA.
https://mesa.org/topics-resources/b2mml/"

Whether B2MML is used or not is a separate decision from incorporating the Data Models.

**Comment by Venkata1920** [comment] 2022-10-25 18:48
Hi @BillBosler, thanks for your interest in CDM and bringing this to our attention. We will review the suggestion and get back on the thread when there is an update.

**Comment by olegovanesyan** [comment] 2022-11-22 19:46
Hi @BillBosler, 
Thank you for reaching out and sharing your feedback - much appreciated! Our current corpus of CDM definitions describes data models of in-market products and if those products support an industry standardized model, so does the CDM. CDM will continue to evolve with products it describes. We have shared your feedback with relevant product teams.

**Comment by dingbx** [comment] 2022-12-13 18:38
Thanks for bringing this schema issue up, closing this issue, please reopen if the issue is still not resolved.

**Closed by dingbx** 2022-12-13 18:38 UTC
