### ISSUE TITLE
Is it possible to connect to Azure Blob Storage?

### ISSUE THREAD

**Issue by jayrumi** [microsoft/CDM#196] opened 2020-11-02 16:56 UTC
Hi,

I want to create remote corpus storage for storing *.cdm.json files in the container in Azure Blob Storage. Is it possible to use ADLS or Remote Adapter for this purpose? If yes, could you provide some examples?

**Comment by dingbx** [comment] 2020-11-02 18:16
Yes, the ADLSAdapter is for this purpose.

In samples folder, we have a [read-local-save-adls](https://github.com/microsoft/CDM/issues/196) sample which read a model.json file from the local folder and save it to adls blob storage. It's not exactly the same but the way it initializes an ADLSAdapter and mount it to the corpus could be a reference.

**Comment by jayrumi** [comment] 2020-11-02 18:48
@dingbx ,
I ran this example with my credentials. Maybe there are some incorrect values. Could you check the screenshot?

![image](https://user-images.githubusercontent.com/15921439/97906292-7443f080-1d54-11eb-9b3b-87ae7db20f90.png)

for **client_id** I use Azure storage account name.

And errors which I got:

![image](https://user-images.githubusercontent.com/15921439/97906615-09df8000-1d55-11eb-902c-5e6214649ee6.png)

**Comment by dingbx** [comment] 2020-11-02 21:27
Can you try following hostname and root?
    hostname = 'account.blob.core.windows.net',
    root = '/ms-common-data-model/test'

And in the sample's sample-data/model.json, the placeholder field <ACCOUNT-NAME> needs to be replaced as your account name, since it will be checked in the ADLSAdapter.

There are some other details that you might need to be aware of in the [README.md](https://github.com/microsoft/CDM/blob/master/samples/4-read-local-save-adls/README.md).

**Comment by jayrumi** [comment] 2020-11-04 07:12
hi @dingbx ,

I tried to do all steps mentioned by you and I got the next error:

`_2020-11-04 09:49:19,243	ERROR	logger.py:47	_log	2020/11/04 06:49:19,2422 | PersistenceLayer | Failed to write to the file 'model.json' for reason 'Get Token request returned http error: 400 and server response: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier '<CLIENT_ID>' was not found in the directory '<TENANT_ID>'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\r\nTrace ID: 5febff78-b7f4-4885-95ac-a66254607600\r\nCorrelation ID: 5586da25-b5d2-4bd6-aa91-be1b50919a6f\r\nTimestamp: 2020-11-04 06:49:19Z","error_codes":[700016],"timestamp":"2020-11-04 06:49:19Z","trace_id":"5febff78-b7f4-4885-95ac-a66254607600","correlation_id":"5586da25-b5d2-4bd6-aa91-be1b50919a6f","error_uri":"https://login.windows.net/error?code=700016"}' | _save_document_as_async_`

**Comment by llawwaii** [comment] 2020-11-05 01:10
Hi, 
Are you sure you have access to the blob storage? Could you please check with the settings in your account?

Let me know if you need more help.
Thanks

**Comment by jayrumi** [comment] 2020-11-05 07:43
hi @llawwaii ,
I'm sure that I have access to the Azure Blob Storage. More over I've connected to this blob using the same credentials and Azure Blob Storage library.

**Comment by dingbx** [comment] 2020-11-07 00:15
Hi @jayrumi ,

I think the problem is that you mentioned 'for client_id I use Azure storage account name',
your client id should be a id with the same length as your tenant id.

**Comment by victor-gutemberg** [comment] 2020-11-16 22:46
Closing due to lack of response. Please reopen if necessary.

**Closed** 2020-11-16 22:47 UTC
